Chargez dans pandas les données disponibles à l'URL suivant:   
https://raw.githubusercontent.com/arx-deidentifier/arx/master/data/adult.csv

Votre travail est maintenant de prédire la variable binaire *salary-class*. Avant d'utiliser un algorithme prédictif, vous allez devoir retravailler vos données (utilisation de la dummification et du labelencoder).

Pour la prédiction, vous devrez mettre en place un régression logistique (pour laquelle il y a tout plein de paramètres https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).   
Cependant vous allez devoir optimiser l'algorithme en créant une grille de paramètres et en utilisant la fonction GridSearchCV de sklearn (https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).

Bon courage !

*P.S: si vous avez fini, créez un pipeline de sorte à optimiser l'algorithme prédictif et le preprocessing simultanément.*

In [0]:
# import modules 

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [0]:
url = "https://raw.githubusercontent.com/arx-deidentifier/arx/master/data/adult.csv"
df = pd.read_csv(url, sep=';')

In [41]:
df.describe(include='all').T

count unique                 top   freq  ...  25%  50%  75%  max
sex             30162      2                Male  20380  ...  NaN  NaN  NaN  NaN
age             30162    NaN                 NaN    NaN  ...   28   37   47   90
race            30162      5               White  25933  ...  NaN  NaN  NaN  NaN
marital-status  30162      7  Married-civ-spouse  14065  ...  NaN  NaN  NaN  NaN
education       30162     16             HS-grad   9840  ...  NaN  NaN  NaN  NaN
native-country  30162     41       United-States  27504  ...  NaN  NaN  NaN  NaN
workclass       30162      7             Private  22286  ...  NaN  NaN  NaN  NaN
occupation      30162     14      Prof-specialty   4038  ...  NaN  NaN  NaN  NaN
salary-class    30162      2               <=50K  22654  ...  NaN  NaN  NaN  NaN

[9 rows x 11 columns]

In [42]:
df.head()

sex  age   race  ...         workclass         occupation salary-class
0    Male   39  White  ...         State-gov       Adm-clerical        <=50K
1    Male   50  White  ...  Self-emp-not-inc    Exec-managerial        <=50K
2    Male   38  White  ...           Private  Handlers-cleaners        <=50K
3    Male   53  Black  ...           Private  Handlers-cleaners        <=50K
4  Female   28  Black  ...           Private     Prof-specialty        <=50K

[5 rows x 9 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30162 entries, 0 to 30161
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   sex             30162 non-null  object
 1   age             30162 non-null  int64 
 2   race            30162 non-null  object
 3   marital-status  30162 non-null  object
 4   education       30162 non-null  object
 5   native-country  30162 non-null  object
 6   workclass       30162 non-null  object
 7   occupation      30162 non-null  object
 8   salary-class    30162 non-null  object
dtypes: int64(1), object(8)
memory usage: 2.1+ MB


In [44]:
df['salary-class']=pd.get_dummies(df['salary-class'], drop_first= True)

df

sex  age   race  ...         workclass         occupation salary-class
0        Male   39  White  ...         State-gov       Adm-clerical            0
1        Male   50  White  ...  Self-emp-not-inc    Exec-managerial            0
2        Male   38  White  ...           Private  Handlers-cleaners            0
3        Male   53  Black  ...           Private  Handlers-cleaners            0
4      Female   28  Black  ...           Private     Prof-specialty            0
...       ...  ...    ...  ...               ...                ...          ...
30157  Female   27  White  ...           Private       Tech-support            0
30158    Male   40  White  ...           Private  Machine-op-inspct            1
30159  Female   58  White  ...           Private       Adm-clerical            0
30160    Male   22  White  ...           Private       Adm-clerical            0
30161  Female   52  White  ...      Self-emp-inc    Exec-managerial            1

[30162 rows x 9 columns]

In [45]:
df['sex1']=pd.get_dummies(df['sex'], drop_first= True)
df

sex  age   race  ...         occupation salary-class sex1
0        Male   39  White  ...       Adm-clerical            0    1
1        Male   50  White  ...    Exec-managerial            0    1
2        Male   38  White  ...  Handlers-cleaners            0    1
3        Male   53  Black  ...  Handlers-cleaners            0    1
4      Female   28  Black  ...     Prof-specialty            0    0
...       ...  ...    ...  ...                ...          ...  ...
30157  Female   27  White  ...       Tech-support            0    0
30158    Male   40  White  ...  Machine-op-inspct            1    1
30159  Female   58  White  ...       Adm-clerical            0    0
30160    Male   22  White  ...       Adm-clerical            0    1
30161  Female   52  White  ...    Exec-managerial            1    0

[30162 rows x 10 columns]

In [0]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df['race'])
LabelEncoder()
list(le.classes_)
df['race1']=le.transform(df['race'])

In [47]:
df.describe(include='all').T

count unique                 top   freq  ...  25%  50%  75%  max
sex             30162      2                Male  20380  ...  NaN  NaN  NaN  NaN
age             30162    NaN                 NaN    NaN  ...   28   37   47   90
race            30162      5               White  25933  ...  NaN  NaN  NaN  NaN
marital-status  30162      7  Married-civ-spouse  14065  ...  NaN  NaN  NaN  NaN
education       30162     16             HS-grad   9840  ...  NaN  NaN  NaN  NaN
native-country  30162     41       United-States  27504  ...  NaN  NaN  NaN  NaN
workclass       30162      7             Private  22286  ...  NaN  NaN  NaN  NaN
occupation      30162     14      Prof-specialty   4038  ...  NaN  NaN  NaN  NaN
salary-class    30162    NaN                 NaN    NaN  ...    0    0    0    1
sex1            30162    NaN                 NaN    NaN  ...    0    1    1    1
race1           30162    NaN                 NaN    NaN  ...    4    4    4    4

[11 rows x 11 columns]

In [0]:
colonne = ['race', 'marital-status', 'education',	'native-country',	'workclass'	, 'occupation']
le = preprocessing.LabelEncoder()

for i in colonne:
  name= i+"1"
  le.fit(df[i])
  LabelEncoder()
  list(le.classes_)
  df[name]=le.transform(df[i])

In [49]:
df.head()

sex  age   race  ... native-country1 workclass1 occupation1
0    Male   39  White  ...              38          5           0
1    Male   50  White  ...              38          4           3
2    Male   38  White  ...              38          2           5
3    Male   53  Black  ...              38          2           5
4  Female   28  Black  ...               4          2           9

[5 rows x 16 columns]

In [50]:
df.columns

Index(['sex', 'age', 'race', 'marital-status', 'education', 'native-country',
       'workclass', 'occupation', 'salary-class', 'sex1', 'race1',
       'marital-status1', 'education1', 'native-country1', 'workclass1',
       'occupation1'],
      dtype='object')

In [0]:
# GRIDSEARCH

from sklearn.model_selection import GridSearchCV

X = df[['age', 'sex1', 'race1', 'marital-status1', 'education1', 
        'native-country1', 'workclass1', 'occupation1']]
y = df['salary-class']

from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
#regression logistique
from sklearn.linear_model import LogisticRegression
reglog = LogisticRegression(random_state=0)
reglogModel = reglog.fit(X, y)
reglogModel.predict(X)
#array([0, 0])
#>>> clf.predict_proba(X[:2, :])
#array([[9.8...e-01, 1.8...e-02, 1.4...e-08],
#       [9.7...e-01, 2.8...e-02, ...e-08]])
#>>> clf.score(X, y)
#0.97...

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
# parametres = { 'C' : [1.0,2.0,3.0,4.0], 'intercept_scaling': [1.0,2.0]}
parametres = {"C":np.logspace(-3,3,7), "penalty":["l1","l2"]}
gsearch = GridSearchCV(reglog, parametres, cv = 5, scoring = 'accuracy', verbose = True)

In [58]:
gsearch.fit(X,y)

Fitting 5 folds for each of 14 candidates, totalling 70 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940:

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=0, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=True)