# Numpy : Introduction

**Numpy allows you to manipulate data in the form of an array.**

**Perform the missions below with Numpy.**

In [0]:
import numpy as np
import random as rd

## Mission 1: 
Show Numpy's version

In [0]:
np.__version__

'1.18.2'

## Mission 2: 
Create a Numpy array of length 3, filled with floats worth 0.x, x can take any value


In [0]:
np.random.random(3)

array([0.74568452, 0.71498176, 0.78172727])

## Mission 3: 
Create a function that with the random.random() method will display 10 random variables strictly greater than 0.25


In [0]:
def random10():
  for i in range(10):
    j = 0
    while j == 0:
      x = rd.random()
      if x > 0.25:
        print(x)
        j += 1

random10()

0.9342684014982575
0.3926572705333984
0.46080853201921634
0.9051102016921471
0.6586916344901957
0.5980308323994891
0.8416562388564104
0.7817581040075764
0.5170051483536454
0.6832781199937311


## Mission 4:
What does the np.empty() method do? You don't just have to copy the doc, but explain it in French


In [0]:
"""
La fonction np.empty() 
permet de retourné une nouvelle matrice avec la forme 
(int ou tuple d'int), le type de data (float, int, ...) et l'ordre 
('C' pour les lignes ou 'F' pour les colonnes) que l'on souhaite.

e.g., pour générer une matrice 3x3 remplie d'entiers : 

    np.empty([3, 3], int)
    >>> array([[4586130515970179488, 4603696339980804161, 4599805920319293792],
               [4604559521312379276, 4602434346151053670, 4597522998987998200],
               [4606579618460449132, 4603567534742580644, 4600046543110464722]])
"""

np.empty([3, 3], int)

array([[           50308080,                  54,          4294967295],
       [7147042649926496103, 7451595014149599084, 3636198724363187569],
       [7291168867612782639, 8028075837187318638, 7451599682962415470]])

## Mission 5: 
Create an array filled with 7 zeros of float type


In [0]:
np.random.uniform(0.0, 0.0, 7)

array([0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

## Mission 6: 
Create an array filled with 10 random digits of type int


In [0]:
array = np.empty(10, int)
print(array)

[           65471712                  54          4294967295
 7147042649926496103 7451595014149599084 3636198724363187569
 7291168867612782639 8028075837187318638 7451599682962415470
     122545876660270]


## Mission 7: 
Create an array that will contain 70 values randomly selected from the numbers: 0, 1, 2, 3, 4, 5, 6, 7.


In [0]:
array2 = np.random.randint(0, 8, size = 70)
print(array2)

[7 6 5 6 3 5 3 2 4 0 6 7 7 0 3 3 4 0 3 4 6 4 7 1 4 7 3 4 0 7 0 1 0 1 2 3 0
 6 5 6 0 6 1 0 1 6 4 2 4 3 7 7 7 2 6 5 0 5 3 6 5 0 3 0 1 7 1 7 3 6]


## Mission 8:
Uses the sciling operator to access items between position 3 and 6 inclusive of mission 6


In [0]:
array[3:7]

array([34269504, 34268544, 34268304, 34268064])

## Mission 9: 
Uses a method to return the index of the minimum element of the array of mission 7


In [0]:
def indexMin(array):
  liste = []
  for i in range(array.size):
    if array[i] == array.min():
      liste.append(i)
  return liste

indexMin(array2)

[9, 13, 17, 28, 30, 32, 36, 40, 43, 56, 61, 63]

## Mission 10: 
Using a numpy method, returns the indexes of values greater than the median value of the array of mission 6


In [0]:
[x for x in range(array.size) if array[x] > np.median(array)]

[0, 3, 4, 5, 6]

## Mission 11: 
- After creating 3 arrays filled with random int's, which you will place in an array
- Create a function that will go through the elements of the 3 arrays in turn.
- This will give : Element 1 of arrays 1, 2 and 3. Element 2 of array 1, 2 and 3...

In [0]:
int_array = np.array([[rd.randint(0, 100), rd.randint(0, 100), rd.randint(0, 100)], 
                      [rd.randint(0, 100), rd.randint(0, 100), rd.randint(0, 100)], 
                      [rd.randint(0, 100), rd.randint(0, 100), rd.randint(0, 100)]])
print(int_array)

def enumArray(array):
  for i in range(len(array)):
    print('Element {}'.format(i +1))
    print(array[0][i])
    print(array[1][i])
    print(array[2][i])
    print()

enumArray(int_array)

[[48  8 34]
 [ 8 51 89]
 [82 47 70]]
Element 1
48
8
82

Element 2
8
51
47

Element 3
34
89
70



In [0]:
a1 = np.random.randint(0, 100, (2, 5))
a2 = np.random.randint(0, 100, (2, 5))
a3 = np.random.randint(0, 100, (2, 5))

print(a1, "\n", a2, "\n", a3, "\n")
np.stack((a1, a2, a3), 2)

[[92 15 18 13 35]
 [ 1 51 29  7 11]] 
 [[21 72 42 68 99]
 [75  2 30 98 43]] 
 [[85 39 80 67 71]
 [54 17 33 34  2]] 



array([[[92, 21, 85],
        [15, 72, 39],
        [18, 42, 80],
        [13, 68, 67],
        [35, 99, 71]],

       [[ 1, 75, 54],
        [51,  2, 17],
        [29, 30, 33],
        [ 7, 98, 34],
        [11, 43,  2]]])

## Mission 12: 
- Create an array and fill it with 20 float random values.
- Create a function that will browse the array and indicate the smallest and largest value in the array.


In [0]:
float_array = np.empty([])

def minNmax_array(array):
  print('min:', array.min())
  print('max:', array.max())

minNmax_array(float_array)

min: 5e-323
max: 5e-323


## Mission 13: 
- Create 2 arrays, randomly fill them with 20 int type values between 0 and 10.
- Create a function that will run through each array with a while loop.
- At each turn of the loop the function will compare the values of the 2 arrays located at the same position.
- In order to return the index to which the values of the 2 arrays are equal.
- If no value is equal to the same position in the 2 arrays, return the message: "No value in common".



In [0]:
array1 = np.random.randint(0, 10, 20)
array2 = np.random.randint(0, 10, 20)

def arrays_comparison(arr1, arr2):
  i = 0
  it = max(arr1.size, arr2.size)
  liste = []
  while i <= it -1:
    if arr1[i] == arr2[i]:
      liste.append(i)
    i += 1
  if len(liste) != 0: 
    return "Common values at index:", liste
  else:
    return "No common values"

arrays_comparison(array1, array2)

('Common values at index:', [7, 12, 15])